DELETE FROM hospital_charges;
DELETE FROM consultation_fees;

INSERT INTO consultation_fees (consultation_type, fee_amount, is_active) VALUES
('New Consultation', 500, 1),
('Follow-up', 300, 1),
('Specialist Consultation', 1000, 1),
('Emergency Consultation', 800, 1),
('Tele-consultation', 400, 1),
('Second Opinion', 1500, 1);

INSERT INTO hospital_charges (charge_name, charge_category, default_price) VALUES
('Registration Fee', 'Admin', 100),
('Admission Charges', 'Admin', 200),
('Medical Record Charges', 'Admin', 50),
('Discharge Summary Charges', 'Admin', 100),
('Medical Certificate Fee', 'Admin', 200),
('Insurance Form Processing', 'Admin', 150),
('Room Rent - General Ward (per day)', 'Room', 1500),
('Room Rent - Semi-Private (per day)', 'Room', 3000),
('Room Rent - Private AC (per day)', 'Room', 5000),
('Room Rent - Deluxe (per day)', 'Room', 8000),
('Room Rent - Suite (per day)', 'Room', 12000),
('Room Rent - ICU (per day)', 'Room', 10000),
('Room Rent - NICU (per day)', 'Room', 12000),
('Room Rent - CCU (per day)', 'Room', 10000),
('Room Rent - HDU (per day)', 'Room', 7000),
('Day Care Charges', 'Room', 2000),
('Extra Bed / Attendant Charges (per day)', 'Room', 500),
('Diet / Food Charges (per day)', 'Room', 300),
('Consultant Visit (per visit)', 'Professional', 500),
('Specialist Opinion', 'Professional', 1000),
('Surgeon Charges', 'Professional', 0),
('Assistant Surgeon Charges', 'Professional', 0),
('Anaesthesia Charges', 'Professional', 0),
('Physiotherapist Consultation', 'Professional', 400),
('Dietician Consultation', 'Professional', 300),
('Psychologist Consultation', 'Professional', 800),
('Nursing Charges - General (per day)', 'Nursing', 500),
('Nursing Charges - ICU (per day)', 'Nursing', 1500),
('Special Nursing (per shift)', 'Nursing', 1000),
('Night Nursing Charges', 'Nursing', 800),
('Complete Blood Count (CBC)', 'Lab', 300),
('Blood Sugar (Fasting/PP)', 'Lab', 100),
('HbA1c', 'Lab', 400),
('Lipid Profile', 'Lab', 500),
('Liver Function Test (LFT)', 'Lab', 600),
('Kidney Function Test (KFT/RFT)', 'Lab', 500),
('Thyroid Profile (T3/T4/TSH)', 'Lab', 500),
('Urine Analysis', 'Lab', 150),
('Blood Culture', 'Lab', 600),
('Prothrombin Time (PT/INR)', 'Lab', 300),
('Electrolytes (Na/K/Cl)', 'Lab', 400),
('Serum Creatinine', 'Lab', 200),
('Blood Grouping and Rh Typing', 'Lab', 200),
('HIV / HBsAg / HCV Screening', 'Lab', 800),
('Vitamin D / B12', 'Lab', 600),
('Troponin / CK-MB', 'Lab', 500),
('D-Dimer', 'Lab', 700),
('CRP (C-Reactive Protein)', 'Lab', 400),
('ESR', 'Lab', 100),
('Uric Acid', 'Lab', 200),
('X-Ray (Single View)', 'Radiology', 400),
('X-Ray (Two Views)', 'Radiology', 600),
('Ultrasound (USG) Abdomen', 'Radiology', 1200),
('Ultrasound (USG) Pelvis', 'Radiology', 1000),
('CT Scan - Plain', 'Radiology', 3500),
('CT Scan - Contrast', 'Radiology', 5000),
('MRI - Plain', 'Radiology', 6000),
('MRI - Contrast', 'Radiology', 8000),
('HRCT Chest', 'Radiology', 4000),
('Mammography', 'Radiology', 1500),
('Bone Densitometry (DEXA)', 'Radiology', 2000),
('ECG (12-Lead)', 'Cardiac', 300),
('2D Echocardiography', 'Cardiac', 2000),
('TMT / Stress Test', 'Cardiac', 1500),
('Holter Monitoring (24hr)', 'Cardiac', 3000),
('Coronary Angiography', 'Cardiac', 15000),
('EEG (Electroencephalogram)', 'Neuro', 1500),
('EMG / NCV Study', 'Neuro', 2500),
('Endoscopy (Upper GI)', 'Endoscopy', 3000),
('Colonoscopy', 'Endoscopy', 5000),
('Bronchoscopy', 'Endoscopy', 4000),
('Spirometry / PFT', 'Pulmonology', 800),
('IV Fluids Administration', 'Procedure', 200),
('Injection Charges (IV/IM)', 'Procedure', 100),
('Blood Transfusion (per unit)', 'Procedure', 1500),
('Platelet Transfusion', 'Procedure', 3000),
('Dressing Charges - Minor', 'Procedure', 300),
('Dressing Charges - Major', 'Procedure', 800),
('Catheterization (Urinary)', 'Procedure', 500),
('Central Line Insertion', 'Procedure', 3000),
('Lumbar Puncture', 'Procedure', 2000),
('Biopsy Charges', 'Procedure', 3000),
('Paracentesis / Ascitic Tap', 'Procedure', 1500),
('Pleural Tap / Thoracentesis', 'Procedure', 2000),
('Suturing (Minor)', 'Procedure', 500),
('Suturing (Major)', 'Procedure', 1500),
('Plaster / Cast Application', 'Procedure', 1000),
('Wound Debridement', 'Procedure', 2000),
('Haemodialysis (per session)', 'Dialysis', 3000),
('Peritoneal Dialysis', 'Dialysis', 2500),
('Chemotherapy Administration', 'Oncology', 0),
('Radiotherapy (per session)', 'Oncology', 0),
('OT Charges - Minor', 'OT', 3000),
('OT Charges - Major', 'OT', 8000),
('OT Charges - Super Major', 'OT', 15000),
('OT Consumables / Disposables', 'OT', 0),
('Surgical Appliances / Implants', 'OT', 0),
('Suture Material', 'OT', 500),
('Laparoscopy Charges', 'OT', 5000),
('Oxygen (per hour)', 'Oxygen', 100),
('Oxygen (per day)', 'Oxygen', 1500),
('Ventilator Charges (per day)', 'Ventilator', 5000),
('BiPAP / CPAP (per day)', 'Ventilator', 3000),
('Nebulization', 'Oxygen', 150),
('High Flow Nasal Cannula (per day)', 'Oxygen', 2500),
('Physiotherapy Session', 'Physio', 500),
('Occupational Therapy', 'Physio', 400),
('Speech Therapy', 'Physio', 500),
('Rehabilitation Session', 'Physio', 600),
('Emergency Room Charges', 'Emergency', 1000),
('Emergency Consultation', 'Emergency', 800),
('Trauma Care Charges', 'Emergency', 2000),
('Resuscitation Charges', 'Emergency', 5000),
('Defibrillation', 'Emergency', 3000),
('Emergency Intubation', 'Emergency', 2000),
('Ambulance - Basic (within city)', 'Ambulance', 1500),
('Ambulance - AC (within city)', 'Ambulance', 2500),
('Ambulance - Advanced Life Support', 'Ambulance', 5000),
('Ambulance - Per KM (outstation)', 'Ambulance', 25),
('Medicines (as per pharmacy bill)', 'Pharmacy', 0),
('Surgical Consumables', 'Consumables', 0),
('Disposables / PPE Kit', 'Consumables', 500),
('Gloves / Syringes / Cannula', 'Consumables', 0),
('Documentation Charges', 'Misc', 100),
('Photocopying Charges', 'Misc', 50),
('Courier Charges (reports)', 'Misc', 100),
('Miscellaneous Charges', 'Misc', 0);
