-- ================================================================
-- CAREPOINT HOSPITAL — WORLD-CLASS BILLING CHARGES (400+ Items)
-- Modelled after Apollo, Fortis, AIIMS, Max Healthcare, Medanta
-- ================================================================

DELETE FROM hospital_charges;
DELETE FROM consultation_fees;

-- ═══ CONSULTATION FEES (18) ═══
INSERT INTO consultation_fees (consultation_type, fee_amount, is_active) VALUES
('New Consultation', 500, 1),
('Follow-up Consultation', 300, 1),
('Specialist Consultation', 1000, 1),
('Super Specialist Consultation', 1500, 1),
('Emergency Consultation', 800, 1),
('Tele-consultation (Video)', 400, 1),
('Tele-consultation (Phone)', 300, 1),
('Second Opinion', 2000, 1),
('Paediatric Consultation', 600, 1),
('Gynaecology Consultation', 700, 1),
('Dental Consultation', 500, 1),
('Dermatology Consultation', 600, 1),
('Psychiatry Consultation', 1000, 1),
('Oncology Consultation', 1500, 1),
('Cardiology Consultation', 1200, 1),
('Neurology Consultation', 1200, 1),
('Orthopaedic Consultation', 800, 1),
('Ophthalmology Consultation', 600, 1);

INSERT INTO hospital_charges (charge_name, charge_category, default_price, is_active) VALUES

-- ═══ REGISTRATION & ADMIN (14) ═══
('Registration Fee', 'Admin', 100, 1),
('Admission Charges', 'Admin', 200, 1),
('Re-admission Charges', 'Admin', 150, 1),
('Medical Record Charges', 'Admin', 50, 1),
('Discharge Summary Charges', 'Admin', 100, 1),
('Medical Certificate Fee', 'Admin', 200, 1),
('Fitness Certificate', 'Admin', 300, 1),
('Insurance Form Processing', 'Admin', 150, 1),
('TPA / Cashless Processing', 'Admin', 200, 1),
('Birth Certificate Fee', 'Admin', 100, 1),
('Death Certificate Fee', 'Admin', 100, 1),
('Transfer Summary Fee', 'Admin', 150, 1),
('Medico-Legal Case (MLC) Fee', 'Admin', 500, 1),
('Duplicate Bill / Receipt', 'Admin', 50, 1),

-- ═══ ROOM & BOARD (20) ═══
('Room Rent - General Ward (per day)', 'Room', 1500, 1),
('Room Rent - Semi-Private (per day)', 'Room', 3000, 1),
('Room Rent - Private Non-AC (per day)', 'Room', 3500, 1),
('Room Rent - Private AC (per day)', 'Room', 5000, 1),
('Room Rent - Deluxe (per day)', 'Room', 8000, 1),
('Room Rent - Suite (per day)', 'Room', 12000, 1),
('Room Rent - Presidential Suite (per day)', 'Room', 20000, 1),
('Room Rent - ICU (per day)', 'Room', 10000, 1),
('Room Rent - MICU (per day)', 'Room', 10000, 1),
('Room Rent - SICU (per day)', 'Room', 12000, 1),
('Room Rent - NICU (per day)', 'Room', 12000, 1),
('Room Rent - PICU (per day)', 'Room', 10000, 1),
('Room Rent - CCU (per day)', 'Room', 10000, 1),
('Room Rent - HDU (per day)', 'Room', 7000, 1),
('Room Rent - Isolation (per day)', 'Room', 6000, 1),
('Room Rent - Labour Room (per day)', 'Room', 5000, 1),
('Day Care Charges', 'Room', 2000, 1),
('Extra Bed / Attendant (per day)', 'Room', 500, 1),
('Diet / Food Charges (per day)', 'Room', 300, 1),
('Linen Charges', 'Room', 100, 1),

-- ═══ DOCTOR / PROFESSIONAL FEES (20) ═══
('Consultant Visit (per visit)', 'Professional', 500, 1),
('Specialist Opinion', 'Professional', 1000, 1),
('Super Specialist Opinion', 'Professional', 1500, 1),
('Surgeon Charges - Minor', 'Professional', 5000, 1),
('Surgeon Charges - Major', 'Professional', 15000, 1),
('Surgeon Charges - Super Major', 'Professional', 25000, 1),
('Assistant Surgeon Charges', 'Professional', 5000, 1),
('Anaesthesia Charges - Local', 'Professional', 1000, 1),
('Anaesthesia Charges - Spinal', 'Professional', 3000, 1),
('Anaesthesia Charges - General', 'Professional', 5000, 1),
('Anaesthesia - Epidural', 'Professional', 4000, 1),
('Physiotherapist Consultation', 'Professional', 400, 1),
('Dietician Consultation', 'Professional', 300, 1),
('Psychologist / Psychiatrist', 'Professional', 800, 1),
('Dental Surgeon Charges', 'Professional', 0, 1),
('Ophthalmologist Charges', 'Professional', 0, 1),
('ENT Specialist Charges', 'Professional', 0, 1),
('Paediatrician Visit', 'Professional', 600, 1),
('Gynaecologist Visit', 'Professional', 700, 1),
('Intensivist / Critical Care', 'Professional', 1500, 1),

-- ═══ NURSING (10) ═══
('Nursing Charges - General (per day)', 'Nursing', 500, 1),
('Nursing Charges - ICU (per day)', 'Nursing', 1500, 1),
('Nursing Charges - NICU (per day)', 'Nursing', 2000, 1),
('Special Nursing (per shift 8hr)', 'Nursing', 1000, 1),
('Night Nursing Charges', 'Nursing', 800, 1),
('Nursing Procedure Charges', 'Nursing', 300, 1),
('Home Nursing Visit', 'Nursing', 1500, 1),
('Wound Care / Dressing by Nurse', 'Nursing', 200, 1),
('IV Line Maintenance (per day)', 'Nursing', 150, 1),
('Patient Monitoring (per hour)', 'Nursing', 200, 1),

-- ═══ LAB - HAEMATOLOGY (16) ═══
('Complete Blood Count (CBC)', 'Lab-Haematology', 300, 1),
('Haemoglobin (Hb)', 'Lab-Haematology', 100, 1),
('Total WBC Count', 'Lab-Haematology', 100, 1),
('Differential Count (DC)', 'Lab-Haematology', 100, 1),
('Platelet Count', 'Lab-Haematology', 150, 1),
('ESR (Erythrocyte Sedimentation Rate)', 'Lab-Haematology', 100, 1),
('Peripheral Blood Smear', 'Lab-Haematology', 200, 1),
('Reticulocyte Count', 'Lab-Haematology', 200, 1),
('Prothrombin Time (PT/INR)', 'Lab-Haematology', 300, 1),
('APTT', 'Lab-Haematology', 350, 1),
('Bleeding Time / Clotting Time', 'Lab-Haematology', 150, 1),
('Blood Grouping and Rh Typing', 'Lab-Haematology', 200, 1),
('Cross Match', 'Lab-Haematology', 300, 1),
('Coombs Test (Direct/Indirect)', 'Lab-Haematology', 400, 1),
('Fibrinogen Level', 'Lab-Haematology', 500, 1),
('G6PD Screening', 'Lab-Haematology', 400, 1),

-- ═══ LAB - BIOCHEMISTRY (30) ═══
('Blood Sugar - Fasting', 'Lab-Biochemistry', 100, 1),
('Blood Sugar - Post Prandial (PP)', 'Lab-Biochemistry', 100, 1),
('Blood Sugar - Random', 'Lab-Biochemistry', 80, 1),
('Glucose Tolerance Test (GTT)', 'Lab-Biochemistry', 400, 1),
('HbA1c (Glycated Haemoglobin)', 'Lab-Biochemistry', 400, 1),
('Fructosamine', 'Lab-Biochemistry', 500, 1),
('Lipid Profile (Complete)', 'Lab-Biochemistry', 500, 1),
('HDL Cholesterol', 'Lab-Biochemistry', 150, 1),
('LDL Cholesterol (Direct)', 'Lab-Biochemistry', 200, 1),
('Triglycerides', 'Lab-Biochemistry', 150, 1),
('Liver Function Test (LFT)', 'Lab-Biochemistry', 600, 1),
('Kidney Function Test (KFT/RFT)', 'Lab-Biochemistry', 500, 1),
('Serum Creatinine', 'Lab-Biochemistry', 200, 1),
('Blood Urea / BUN', 'Lab-Biochemistry', 150, 1),
('Serum Uric Acid', 'Lab-Biochemistry', 200, 1),
('Serum Electrolytes (Na/K/Cl)', 'Lab-Biochemistry', 400, 1),
('Serum Calcium', 'Lab-Biochemistry', 200, 1),
('Ionized Calcium', 'Lab-Biochemistry', 350, 1),
('Serum Magnesium', 'Lab-Biochemistry', 250, 1),
('Serum Phosphorus', 'Lab-Biochemistry', 200, 1),
('Serum Protein / Albumin', 'Lab-Biochemistry', 250, 1),
('Bilirubin (Total/Direct/Indirect)', 'Lab-Biochemistry', 200, 1),
('SGOT / AST', 'Lab-Biochemistry', 150, 1),
('SGPT / ALT', 'Lab-Biochemistry', 150, 1),
('Alkaline Phosphatase (ALP)', 'Lab-Biochemistry', 200, 1),
('GGT (Gamma GT)', 'Lab-Biochemistry', 300, 1),
('Amylase', 'Lab-Biochemistry', 350, 1),
('Lipase', 'Lab-Biochemistry', 400, 1),
('LDH (Lactate Dehydrogenase)', 'Lab-Biochemistry', 400, 1),
('CPK / CK-MB', 'Lab-Biochemistry', 500, 1),

-- ═══ LAB - SEROLOGY / IMMUNOLOGY (18) ═══
('Thyroid Profile (T3/T4/TSH)', 'Lab-Serology', 500, 1),
('Free T3', 'Lab-Serology', 250, 1),
('Free T4', 'Lab-Serology', 250, 1),
('TSH (Ultra-sensitive)', 'Lab-Serology', 300, 1),
('Anti-TPO Antibodies', 'Lab-Serology', 600, 1),
('Vitamin D (25-OH)', 'Lab-Serology', 600, 1),
('Vitamin B12', 'Lab-Serology', 600, 1),
('Folate / Folic Acid', 'Lab-Serology', 500, 1),
('Ferritin', 'Lab-Serology', 500, 1),
('Iron Studies (TIBC/Iron/Ferritin)', 'Lab-Serology', 800, 1),
('CRP (C-Reactive Protein)', 'Lab-Serology', 400, 1),
('hs-CRP (High Sensitivity)', 'Lab-Serology', 600, 1),
('Procalcitonin', 'Lab-Serology', 1500, 1),
('Troponin I / T', 'Lab-Serology', 500, 1),
('D-Dimer', 'Lab-Serology', 700, 1),
('NT-proBNP', 'Lab-Serology', 1500, 1),
('PSA (Prostate Specific Antigen)', 'Lab-Serology', 600, 1),
('ANA (Anti-Nuclear Antibody)', 'Lab-Serology', 800, 1),

-- ═══ LAB - MICROBIOLOGY (12) ═══
('Blood Culture and Sensitivity', 'Lab-Microbiology', 600, 1),
('Urine Culture and Sensitivity', 'Lab-Microbiology', 500, 1),
('Sputum Culture', 'Lab-Microbiology', 500, 1),
('Wound Swab Culture', 'Lab-Microbiology', 500, 1),
('Stool Culture', 'Lab-Microbiology', 500, 1),
('Throat Swab Culture', 'Lab-Microbiology', 400, 1),
('AFB Staining / TB Culture', 'Lab-Microbiology', 400, 1),
('GeneXpert (TB PCR)', 'Lab-Microbiology', 1500, 1),
('Fungal Culture', 'Lab-Microbiology', 600, 1),
('Sensitivity Testing (MIC)', 'Lab-Microbiology', 800, 1),
('COVID-19 RT-PCR', 'Lab-Microbiology', 500, 1),
('COVID-19 Rapid Antigen', 'Lab-Microbiology', 200, 1),

-- ═══ LAB - SCREENING / INFECTIOUS (12) ═══
('HIV 1 & 2 Screening', 'Lab-Screening', 300, 1),
('HBsAg (Hepatitis B)', 'Lab-Screening', 300, 1),
('HCV (Hepatitis C) Antibody', 'Lab-Screening', 400, 1),
('Hepatitis B Viral Load (HBV DNA)', 'Lab-Screening', 3000, 1),
('VDRL / RPR (Syphilis)', 'Lab-Screening', 200, 1),
('Dengue NS1 Antigen', 'Lab-Screening', 500, 1),
('Dengue IgM / IgG', 'Lab-Screening', 600, 1),
('Malaria (Rapid/Smear)', 'Lab-Screening', 300, 1),
('Widal Test (Typhoid)', 'Lab-Screening', 200, 1),
('Chikungunya IgM', 'Lab-Screening', 500, 1),
('Leptospira IgM', 'Lab-Screening', 600, 1),
('Scrub Typhus IgM', 'Lab-Screening', 600, 1),

-- ═══ LAB - URINE & STOOL (10) ═══
('Urine Routine & Microscopy', 'Lab-Urine', 150, 1),
('Urine Microalbumin', 'Lab-Urine', 400, 1),
('24hr Urine Protein', 'Lab-Urine', 300, 1),
('24hr Urine Creatinine', 'Lab-Urine', 300, 1),
('Urine Pregnancy Test (UPT)', 'Lab-Urine', 100, 1),
('Urine Drug Screening', 'Lab-Urine', 1000, 1),
('Urine Electrolytes', 'Lab-Urine', 400, 1),
('Stool Routine & Microscopy', 'Lab-Urine', 150, 1),
('Stool Occult Blood', 'Lab-Urine', 200, 1),
('Stool for Ova & Cyst', 'Lab-Urine', 150, 1),

-- ═══ LAB - HORMONES & TUMOR MARKERS (16) ═══
('Cortisol (Morning)', 'Lab-Hormones', 500, 1),
('Cortisol (Evening)', 'Lab-Hormones', 500, 1),
('Prolactin', 'Lab-Hormones', 500, 1),
('FSH (Follicle Stimulating Hormone)', 'Lab-Hormones', 350, 1),
('LH (Luteinizing Hormone)', 'Lab-Hormones', 350, 1),
('Estradiol', 'Lab-Hormones', 400, 1),
('Progesterone', 'Lab-Hormones', 400, 1),
('Testosterone (Total)', 'Lab-Hormones', 500, 1),
('DHEA-S', 'Lab-Hormones', 600, 1),
('Insulin (Fasting)', 'Lab-Hormones', 500, 1),
('Beta HCG (Pregnancy)', 'Lab-Hormones', 500, 1),
('CA-125 (Ovarian Marker)', 'Lab-Hormones', 800, 1),
('CA 19-9 (Pancreatic Marker)', 'Lab-Hormones', 800, 1),
('CEA (Carcinoembryonic Antigen)', 'Lab-Hormones', 700, 1),
('AFP (Alpha Fetoprotein)', 'Lab-Hormones', 600, 1),
('CA 15-3 (Breast Cancer Marker)', 'Lab-Hormones', 800, 1),

-- ═══ LAB - SPECIAL / GENETIC (8) ═══
('ABG (Arterial Blood Gas)', 'Lab-Special', 500, 1),
('Serum Lactate', 'Lab-Special', 400, 1),
('Osmolality (Serum/Urine)', 'Lab-Special', 500, 1),
('Hemoglobin Electrophoresis', 'Lab-Special', 800, 1),
('Protein Electrophoresis', 'Lab-Special', 1200, 1),
('Flow Cytometry', 'Lab-Special', 3000, 1),
('Bone Marrow Aspiration Study', 'Lab-Special', 2000, 1),
('Chromosomal Analysis / Karyotype', 'Lab-Special', 5000, 1),

-- ═══ LAB - HISTOPATHOLOGY (8) ═══
('Biopsy - Histopathology (Small)', 'Lab-Histopath', 800, 1),
('Biopsy - Histopathology (Large)', 'Lab-Histopath', 1500, 1),
('FNAC (Fine Needle Aspiration)', 'Lab-Histopath', 600, 1),
('Frozen Section', 'Lab-Histopath', 2000, 1),
('Immunohistochemistry (IHC)', 'Lab-Histopath', 3000, 1),
('Pap Smear (Cytology)', 'Lab-Histopath', 400, 1),
('Body Fluid Cytology', 'Lab-Histopath', 500, 1),
('Semen Analysis', 'Lab-Histopath', 400, 1),

-- ═══ RADIOLOGY - X-RAY (10) ═══
('X-Ray - Single View', 'Radiology', 400, 1),
('X-Ray - Two Views', 'Radiology', 600, 1),
('X-Ray - Chest PA', 'Radiology', 400, 1),
('X-Ray - Chest AP/Lateral', 'Radiology', 500, 1),
('X-Ray - Abdomen Erect', 'Radiology', 500, 1),
('X-Ray - Spine (Cervical/Lumbar)', 'Radiology', 500, 1),
('X-Ray - Pelvis', 'Radiology', 400, 1),
('X-Ray - Extremity / Limb', 'Radiology', 400, 1),
('X-Ray - Skull', 'Radiology', 400, 1),
('X-Ray - KUB Region', 'Radiology', 400, 1),

-- ═══ RADIOLOGY - ULTRASOUND (12) ═══
('USG - Abdomen (Complete)', 'Ultrasound', 1200, 1),
('USG - Abdomen (Upper)', 'Ultrasound', 800, 1),
('USG - Pelvis', 'Ultrasound', 1000, 1),
('USG - KUB (Kidney/Ureter/Bladder)', 'Ultrasound', 1000, 1),
('USG - Obstetric (Pregnancy)', 'Ultrasound', 1200, 1),
('USG - NT Scan (Nuchal Translucency)', 'Ultrasound', 1500, 1),
('USG - Anomaly Scan', 'Ultrasound', 2000, 1),
('USG - Growth Scan', 'Ultrasound', 1200, 1),
('USG - Doppler Study', 'Ultrasound', 2000, 1),
('USG - Thyroid / Neck', 'Ultrasound', 800, 1),
('USG - Breast', 'Ultrasound', 1000, 1),
('USG - Guided Procedure', 'Ultrasound', 2500, 1),

-- ═══ RADIOLOGY - CT SCAN (10) ═══
('CT Scan - Brain Plain', 'CT-Scan', 3000, 1),
('CT Scan - Brain Contrast', 'CT-Scan', 4500, 1),
('CT Scan - Chest Plain', 'CT-Scan', 3500, 1),
('CT Scan - Chest Contrast', 'CT-Scan', 5000, 1),
('CT Scan - Abdomen Plain', 'CT-Scan', 3500, 1),
('CT Scan - Abdomen Contrast', 'CT-Scan', 5000, 1),
('CT Scan - Whole Abdomen (CECT)', 'CT-Scan', 6000, 1),
('HRCT Chest', 'CT-Scan', 4000, 1),
('CT Angiography', 'CT-Scan', 8000, 1),
('CT - KUB / Urogram', 'CT-Scan', 5000, 1),

-- ═══ MRI (10) ═══
('MRI - Brain Plain', 'MRI', 6000, 1),
('MRI - Brain Contrast', 'MRI', 8000, 1),
('MRI - Brain with MRA', 'MRI', 10000, 1),
('MRI - Spine (Cervical)', 'MRI', 5000, 1),
('MRI - Spine (Lumbar)', 'MRI', 5000, 1),
('MRI - Spine (Whole)', 'MRI', 12000, 1),
('MRI - Abdomen', 'MRI', 7000, 1),
('MRI - Pelvis', 'MRI', 6000, 1),
('MRI - Joint / Extremity', 'MRI', 5000, 1),
('MRI - Whole Body', 'MRI', 15000, 1),

-- ═══ SPECIAL IMAGING (6) ═══
('Mammography (Both Breasts)', 'Imaging', 1500, 1),
('Digital Mammography with Tomosynthesis', 'Imaging', 3000, 1),
('Bone Densitometry (DEXA)', 'Imaging', 2000, 1),
('OPG (Dental Panoramic X-Ray)', 'Imaging', 500, 1),
('Contrast Study (Barium Swallow/Meal)', 'Imaging', 1500, 1),
('IVP / IVU (Intravenous Pyelogram)', 'Imaging', 2000, 1),

-- ═══ CARDIAC (14) ═══
('ECG (12-Lead)', 'Cardiac', 300, 1),
('2D Echocardiography', 'Cardiac', 2000, 1),
('2D Echo with Doppler', 'Cardiac', 2500, 1),
('Stress Echocardiography', 'Cardiac', 3500, 1),
('TMT / Treadmill Stress Test', 'Cardiac', 1500, 1),
('Holter Monitoring (24hr)', 'Cardiac', 3000, 1),
('Ambulatory BP Monitoring (ABPM)', 'Cardiac', 1500, 1),
('Coronary Angiography', 'Cardiac', 15000, 1),
('Angioplasty (PTCA) - Single Stent', 'Cardiac', 80000, 1),
('Angioplasty - Drug Eluting Stent', 'Cardiac', 120000, 1),
('Pacemaker Implantation (Single)', 'Cardiac', 100000, 1),
('Pacemaker Implantation (Dual)', 'Cardiac', 150000, 1),
('Cardiac Catheterization', 'Cardiac', 20000, 1),
('CABG (Bypass Surgery)', 'Cardiac', 250000, 1),

-- ═══ NEURO (8) ═══
('EEG (Electroencephalogram)', 'Neuro', 1500, 1),
('EMG / NCV Study', 'Neuro', 2500, 1),
('Video EEG Monitoring', 'Neuro', 5000, 1),
('Evoked Potentials (VEP/BERA/SSEP)', 'Neuro', 2000, 1),
('Nerve Block', 'Neuro', 3000, 1),
('Carotid Doppler', 'Neuro', 2000, 1),
('Transcranial Doppler (TCD)', 'Neuro', 3000, 1),
('Lumbar Puncture with Analysis', 'Neuro', 3000, 1),

-- ═══ ENDOSCOPY / GI (10) ═══
('Upper GI Endoscopy (OGD)', 'Endoscopy', 3000, 1),
('Upper GI Endoscopy with Biopsy', 'Endoscopy', 4000, 1),
('Colonoscopy', 'Endoscopy', 5000, 1),
('Colonoscopy with Polypectomy', 'Endoscopy', 8000, 1),
('Sigmoidoscopy', 'Endoscopy', 3000, 1),
('ERCP (Diagnostic)', 'Endoscopy', 15000, 1),
('ERCP with Stenting', 'Endoscopy', 25000, 1),
('Bronchoscopy', 'Endoscopy', 4000, 1),
('Cystoscopy', 'Endoscopy', 5000, 1),
('EUS (Endoscopic Ultrasound)', 'Endoscopy', 10000, 1),

-- ═══ PULMONOLOGY (6) ═══
('Spirometry / PFT', 'Pulmonology', 800, 1),
('DLCO (Diffusion Capacity)', 'Pulmonology', 1200, 1),
('Sleep Study (Polysomnography)', 'Pulmonology', 5000, 1),
('Thoracentesis', 'Pulmonology', 2000, 1),
('Pleural Biopsy', 'Pulmonology', 3000, 1),
('Bronchial Lavage (BAL)', 'Pulmonology', 3000, 1),

-- ═══ PROCEDURE / TREATMENT (28) ═══
('IV Fluids Administration', 'Procedure', 200, 1),
('Injection Charges (IV/IM/SC)', 'Procedure', 100, 1),
('Insulin Administration', 'Procedure', 50, 1),
('Blood Transfusion (per unit)', 'Procedure', 1500, 1),
('Platelet Transfusion', 'Procedure', 3000, 1),
('FFP Transfusion', 'Procedure', 2000, 1),
('Packed RBC Transfusion', 'Procedure', 1800, 1),
('Cryoprecipitate Transfusion', 'Procedure', 2500, 1),
('Dressing - Minor', 'Procedure', 300, 1),
('Dressing - Major', 'Procedure', 800, 1),
('Dressing - Burn', 'Procedure', 1500, 1),
('Wound Debridement', 'Procedure', 2000, 1),
('Negative Pressure Wound Therapy (VAC)', 'Procedure', 3000, 1),
('Catheterization (Urinary)', 'Procedure', 500, 1),
('Suprapubic Catheterization', 'Procedure', 2000, 1),
('Ryles Tube Insertion', 'Procedure', 300, 1),
('Central Line Insertion', 'Procedure', 3000, 1),
('PICC Line Insertion', 'Procedure', 4000, 1),
('Arterial Line Insertion', 'Procedure', 2000, 1),
('Lumbar Puncture', 'Procedure', 2000, 1),
('Biopsy - FNAC', 'Procedure', 1500, 1),
('Biopsy - Excision', 'Procedure', 3000, 1),
('Paracentesis / Ascitic Tap', 'Procedure', 1500, 1),
('Pleural Tap / Tapping', 'Procedure', 2000, 1),
('Intercostal Drainage (ICD)', 'Procedure', 5000, 1),
('Suturing - Minor (< 5 stitches)', 'Procedure', 500, 1),
('Suturing - Major (> 5 stitches)', 'Procedure', 1500, 1),
('Plaster / Cast Application', 'Procedure', 1000, 1),

-- ═══ DIALYSIS / NEPHROLOGY (6) ═══
('Haemodialysis (per session)', 'Dialysis', 3000, 1),
('Peritoneal Dialysis (per session)', 'Dialysis', 2500, 1),
('CRRT (per day)', 'Dialysis', 15000, 1),
('Plasmapheresis', 'Dialysis', 10000, 1),
('AV Fistula Creation', 'Dialysis', 15000, 1),
('Temporary Dialysis Catheter', 'Dialysis', 5000, 1),

-- ═══ ONCOLOGY (8) ═══
('Chemotherapy Administration', 'Oncology', 0, 1),
('Chemotherapy Port Insertion', 'Oncology', 15000, 1),
('Radiotherapy (per session)', 'Oncology', 0, 1),
('IMRT (per session)', 'Oncology', 0, 1),
('Brachytherapy', 'Oncology', 0, 1),
('PET-CT Scan', 'Oncology', 15000, 1),
('Bone Marrow Biopsy', 'Oncology', 5000, 1),
('Intrathecal Chemotherapy', 'Oncology', 5000, 1),

-- ═══ OPERATION THEATRE (16) ═══
('OT Charges - Minor Surgery', 'OT', 3000, 1),
('OT Charges - Intermediate', 'OT', 5000, 1),
('OT Charges - Major Surgery', 'OT', 8000, 1),
('OT Charges - Super Major', 'OT', 15000, 1),
('OT Charges - Ultra Major / Complex', 'OT', 25000, 1),
('OT Consumables / Disposables', 'OT', 0, 1),
('Surgical Implants / Prosthesis', 'OT', 0, 1),
('Suture Material', 'OT', 500, 1),
('Surgical Stapler', 'OT', 3000, 1),
('Laparoscopy Charges', 'OT', 5000, 1),
('Robotic Surgery Charges', 'OT', 50000, 1),
('Cautery / Electrocautery', 'OT', 1000, 1),
('Harmonic Scalpel Usage', 'OT', 5000, 1),
('Tourniquet Charges', 'OT', 500, 1),
('C-Arm (Fluoroscopy) Usage', 'OT', 3000, 1),
('Operating Microscope Usage', 'OT', 5000, 1),

-- ═══ OXYGEN & VENTILATOR (12) ═══
('Oxygen - Per Hour', 'Oxygen', 100, 1),
('Oxygen - Per Day', 'Oxygen', 1500, 1),
('Oxygen Cylinder Charges', 'Oxygen', 500, 1),
('Nebulization (per session)', 'Oxygen', 150, 1),
('Steam Inhalation', 'Oxygen', 50, 1),
('High Flow Nasal Cannula (HFNC) per day', 'Oxygen', 2500, 1),
('Ventilator Charges (per day)', 'Ventilator', 5000, 1),
('BiPAP / CPAP (per day)', 'Ventilator', 3000, 1),
('NIV (Non-Invasive Ventilation)', 'Ventilator', 4000, 1),
('Tracheostomy Care (per day)', 'Ventilator', 1000, 1),
('Ventilator Weaning Trial', 'Ventilator', 2000, 1),
('ECMO (per day)', 'Ventilator', 50000, 1),

-- ═══ PHYSIOTHERAPY & REHAB (10) ═══
('Physiotherapy Session', 'Physio', 500, 1),
('Occupational Therapy', 'Physio', 400, 1),
('Speech Therapy', 'Physio', 500, 1),
('Rehabilitation Session', 'Physio', 600, 1),
('Chest Physiotherapy', 'Physio', 300, 1),
('Post-Operative Physio', 'Physio', 500, 1),
('TENS / IFT / Ultrasonic Therapy', 'Physio', 300, 1),
('Traction (Cervical/Lumbar)', 'Physio', 300, 1),
('Gait Training / Mobility', 'Physio', 400, 1),
('Aquatic / Hydro Therapy', 'Physio', 800, 1),

-- ═══ EMERGENCY (12) ═══
('Emergency Room Charges', 'Emergency', 1000, 1),
('Emergency Consultation', 'Emergency', 800, 1),
('Emergency Registration', 'Emergency', 200, 1),
('Trauma Care Charges', 'Emergency', 2000, 1),
('Polytrauma Management', 'Emergency', 5000, 1),
('Resuscitation / CPR Charges', 'Emergency', 5000, 1),
('Defibrillation', 'Emergency', 3000, 1),
('Emergency Intubation', 'Emergency', 2000, 1),
('Gastric Lavage', 'Emergency', 1500, 1),
('Poison Management', 'Emergency', 3000, 1),
('Snake Bite / Animal Bite Kit', 'Emergency', 2000, 1),
('Anti-Rabies Vaccination', 'Emergency', 1500, 1),

-- ═══ AMBULANCE (8) ═══
('Ambulance - Basic (within city)', 'Ambulance', 1500, 1),
('Ambulance - AC (within city)', 'Ambulance', 2500, 1),
('Ambulance - Advanced Life Support', 'Ambulance', 5000, 1),
('Ambulance - Cardiac (ACLS)', 'Ambulance', 6000, 1),
('Ambulance - Neonatal', 'Ambulance', 8000, 1),
('Ambulance - Per KM (outstation)', 'Ambulance', 25, 1),
('Air Ambulance (Helicopter)', 'Ambulance', 200000, 1),
('Dead Body Van', 'Ambulance', 2000, 1),

-- ═══ OBSTETRICS & GYNAECOLOGY (14) ═══
('Normal Delivery Charges', 'OB-GYN', 15000, 1),
('Induced Labour Charges', 'OB-GYN', 8000, 1),
('Caesarean Section (LSCS)', 'OB-GYN', 35000, 1),
('Episiotomy Charges', 'OB-GYN', 2000, 1),
('Vacuum / Forceps Delivery', 'OB-GYN', 5000, 1),
('D&C / Evacuation', 'OB-GYN', 5000, 1),
('Hysterectomy (Abdominal)', 'OB-GYN', 40000, 1),
('Hysterectomy (Laparoscopic)', 'OB-GYN', 60000, 1),
('IUD Insertion', 'OB-GYN', 500, 1),
('Pap Smear', 'OB-GYN', 500, 1),
('Colposcopy', 'OB-GYN', 2000, 1),
('Amniocentesis', 'OB-GYN', 5000, 1),
('Tubectomy / Tubal Ligation', 'OB-GYN', 8000, 1),
('IVF Cycle Charges', 'OB-GYN', 100000, 1),

-- ═══ ORTHOPAEDICS (12) ═══
('Fracture Reduction (Closed)', 'Ortho', 3000, 1),
('Fracture Fixation (Open/ORIF)', 'Ortho', 30000, 1),
('Total Knee Replacement (TKR)', 'Ortho', 150000, 1),
('Total Hip Replacement (THR)', 'Ortho', 180000, 1),
('Arthroscopy (Diagnostic)', 'Ortho', 15000, 1),
('Arthroscopic ACL Reconstruction', 'Ortho', 80000, 1),
('Spine Surgery (Discectomy)', 'Ortho', 100000, 1),
('Spine Fusion Surgery', 'Ortho', 200000, 1),
('Traction Charges (per day)', 'Ortho', 500, 1),
('Crepe Bandage / Splint', 'Ortho', 300, 1),
('POP Cast (Plaster of Paris)', 'Ortho', 1500, 1),
('External Fixator Application', 'Ortho', 10000, 1),

-- ═══ UROLOGY (8) ═══
('Cystolithotomy', 'Urology', 20000, 1),
('TURP (Prostate Surgery)', 'Urology', 35000, 1),
('PCNL (Kidney Stone)', 'Urology', 40000, 1),
('URS / RIRS (Stone)', 'Urology', 25000, 1),
('ESWL (Lithotripsy)', 'Urology', 15000, 1),
('Circumcision', 'Urology', 5000, 1),
('Hydrocele Surgery', 'Urology', 10000, 1),
('Nephrectomy', 'Urology', 60000, 1),

-- ═══ OPHTHALMOLOGY (8) ═══
('Cataract Surgery (Phaco)', 'Eye', 15000, 1),
('Cataract Surgery (MICS/Femto)', 'Eye', 30000, 1),
('IOL Implant Charges', 'Eye', 0, 1),
('Retinal Laser (PRP)', 'Eye', 5000, 1),
('Vitrectomy', 'Eye', 40000, 1),
('Glaucoma Surgery', 'Eye', 20000, 1),
('LASIK / Refractive Surgery', 'Eye', 25000, 1),
('Fundoscopy / Retinal Exam', 'Eye', 500, 1),

-- ═══ ENT (10) ═══
('Tonsillectomy', 'ENT', 10000, 1),
('Adenoidectomy', 'ENT', 8000, 1),
('Septoplasty', 'ENT', 15000, 1),
('FESS (Sinus Surgery)', 'ENT', 25000, 1),
('Myringotomy / Grommet', 'ENT', 5000, 1),
('Tympanoplasty', 'ENT', 20000, 1),
('Mastoidectomy', 'ENT', 30000, 1),
('Audiometry / Hearing Test', 'ENT', 500, 1),
('Impedance Audiometry', 'ENT', 600, 1),
('Microlaryngoscopy', 'ENT', 10000, 1),

-- ═══ DENTAL (10) ═══
('Tooth Extraction (Simple)', 'Dental', 500, 1),
('Tooth Extraction (Surgical / Impacted)', 'Dental', 2000, 1),
('Root Canal Treatment (Single Canal)', 'Dental', 3000, 1),
('Root Canal Treatment (Multi Canal)', 'Dental', 5000, 1),
('Dental Crown / Cap', 'Dental', 3000, 1),
('Dental Bridge', 'Dental', 5000, 1),
('Dental Implant', 'Dental', 25000, 1),
('Scaling / Cleaning', 'Dental', 800, 1),
('Tooth Filling (Composite)', 'Dental', 500, 1),
('Denture (Complete)', 'Dental', 8000, 1),

-- ═══ DERMATOLOGY (6) ═══
('Skin Biopsy', 'Dermatology', 1500, 1),
('Cryotherapy', 'Dermatology', 500, 1),
('Electrocautery (Wart/Mole)', 'Dermatology', 1000, 1),
('Chemical Peel', 'Dermatology', 2000, 1),
('Phototherapy / PUVA', 'Dermatology', 500, 1),
('Allergy Testing (Patch Test)', 'Dermatology', 1500, 1),

-- ═══ GENERAL SURGERY (10) ═══
('Appendectomy (Open)', 'Surgery', 15000, 1),
('Appendectomy (Laparoscopic)', 'Surgery', 25000, 1),
('Hernia Repair (Open)', 'Surgery', 15000, 1),
('Hernia Repair (Laparoscopic)', 'Surgery', 30000, 1),
('Cholecystectomy (Laparoscopic)', 'Surgery', 35000, 1),
('Hemorrhoidectomy / Piles', 'Surgery', 15000, 1),
('Fistula Surgery', 'Surgery', 15000, 1),
('Abscess Incision & Drainage', 'Surgery', 3000, 1),
('Lipoma / Cyst Excision', 'Surgery', 5000, 1),
('Thyroidectomy', 'Surgery', 40000, 1),

-- ═══ PHARMACY & CONSUMABLES (10) ═══
('Medicines (as per pharmacy bill)', 'Pharmacy', 0, 1),
('Antibiotics / IV Antibiotics', 'Pharmacy', 0, 1),
('Surgical Consumables', 'Consumables', 0, 1),
('Disposables / PPE Kit', 'Consumables', 500, 1),
('Gloves / Syringes / Cannula Pack', 'Consumables', 100, 1),
('Catheter / Urobag', 'Consumables', 300, 1),
('Blood Bag Charges', 'Consumables', 500, 1),
('Dressing Material', 'Consumables', 200, 1),
('Chest Tube / Drain', 'Consumables', 800, 1),
('Infusion Pump Charges (per day)', 'Consumables', 500, 1),

-- ═══ HEALTH PACKAGES (8) ═══
('Basic Health Checkup Package', 'Health-Package', 1500, 1),
('Comprehensive Health Package', 'Health-Package', 3500, 1),
('Executive Health Package', 'Health-Package', 6000, 1),
('Cardiac Health Package', 'Health-Package', 5000, 1),
('Diabetes Screening Package', 'Health-Package', 2000, 1),
('Women Wellness Package', 'Health-Package', 4000, 1),
('Senior Citizen Package', 'Health-Package', 5000, 1),
('Pre-Employment Health Check', 'Health-Package', 2500, 1),

-- ═══ MISCELLANEOUS (10) ═══
('Documentation Charges', 'Misc', 100, 1),
('Photocopying Charges', 'Misc', 50, 1),
('Courier Charges (reports)', 'Misc', 100, 1),
('Attendant Pass Charges', 'Misc', 50, 1),
('Parking Charges', 'Misc', 50, 1),
('Wheelchair Charges (per day)', 'Misc', 200, 1),
('Walker / Crutch Charges (per day)', 'Misc', 100, 1),
('Mortuary Charges (per day)', 'Misc', 500, 1),
('Embalming Charges', 'Misc', 5000, 1),
('Miscellaneous Charges', 'Misc', 0, 1);
